/*
 * HighFrequencyTrading API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.lykke.hft.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * ErrorResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-06T23:34:32.567+02:00")
public class ErrorResponse {
  @JsonProperty("ErrorMessage")
  private String errorMessage = null;

  @JsonProperty("ModelErrors")
  private Map<String, List<String>> modelErrors = null;

   /**
   * Get errorMessage
   * @return errorMessage
  **/
  @ApiModelProperty(value = "")
  public String getErrorMessage() {
    return errorMessage;
  }

  public ErrorResponse modelErrors(Map<String, List<String>> modelErrors) {
    this.modelErrors = modelErrors;
    return this;
  }

  public ErrorResponse putModelErrorsItem(String key, List<String> modelErrorsItem) {
    if (this.modelErrors == null) {
      this.modelErrors = new HashMap<String, List<String>>();
    }
    this.modelErrors.put(key, modelErrorsItem);
    return this;
  }

   /**
   * Get modelErrors
   * @return modelErrors
  **/
  @ApiModelProperty(value = "")
  public Map<String, List<String>> getModelErrors() {
    return modelErrors;
  }

  public void setModelErrors(Map<String, List<String>> modelErrors) {
    this.modelErrors = modelErrors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorResponse errorResponse = (ErrorResponse) o;
    return Objects.equals(this.errorMessage, errorResponse.errorMessage) &&
        Objects.equals(this.modelErrors, errorResponse.modelErrors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorMessage, modelErrors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorResponse {\n");
    
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    modelErrors: ").append(toIndentedString(modelErrors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

