/*
 * HighFrequencyTrading API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.lykke.hft.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lykke.hft.model.VolumePrice;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * OrderBook
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-06T23:34:32.567+02:00")
public class OrderBook {
  @JsonProperty("AssetPair")
  private String assetPair = null;

  @JsonProperty("IsBuy")
  private Boolean isBuy = null;

  @JsonProperty("Timestamp")
  private DateTime timestamp = null;

  @JsonProperty("Prices")
  private List<VolumePrice> prices = null;

  public OrderBook assetPair(String assetPair) {
    this.assetPair = assetPair;
    return this;
  }

   /**
   * Get assetPair
   * @return assetPair
  **/
  @ApiModelProperty(value = "")
  public String getAssetPair() {
    return assetPair;
  }

  public void setAssetPair(String assetPair) {
    this.assetPair = assetPair;
  }

  public OrderBook isBuy(Boolean isBuy) {
    this.isBuy = isBuy;
    return this;
  }

   /**
   * Get isBuy
   * @return isBuy
  **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getIsBuy() {
    return isBuy;
  }

  public void setIsBuy(Boolean isBuy) {
    this.isBuy = isBuy;
  }

  public OrderBook timestamp(DateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(required = true, value = "")
  public DateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(DateTime timestamp) {
    this.timestamp = timestamp;
  }

  public OrderBook prices(List<VolumePrice> prices) {
    this.prices = prices;
    return this;
  }

  public OrderBook addPricesItem(VolumePrice pricesItem) {
    if (this.prices == null) {
      this.prices = new ArrayList<VolumePrice>();
    }
    this.prices.add(pricesItem);
    return this;
  }

   /**
   * Get prices
   * @return prices
  **/
  @ApiModelProperty(value = "")
  public List<VolumePrice> getPrices() {
    return prices;
  }

  public void setPrices(List<VolumePrice> prices) {
    this.prices = prices;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderBook orderBook = (OrderBook) o;
    return Objects.equals(this.assetPair, orderBook.assetPair) &&
        Objects.equals(this.isBuy, orderBook.isBuy) &&
        Objects.equals(this.timestamp, orderBook.timestamp) &&
        Objects.equals(this.prices, orderBook.prices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assetPair, isBuy, timestamp, prices);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderBook {\n");
    
    sb.append("    assetPair: ").append(toIndentedString(assetPair)).append("\n");
    sb.append("    isBuy: ").append(toIndentedString(isBuy)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    prices: ").append(toIndentedString(prices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

