/*
 * HighFrequencyTrading API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.lykke.hft.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lykke.hft.model.ErrorModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ResponseModelDouble
 *
 * @author niau
 * @version $Id: $Id
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-06T23:34:32.567+02:00")
public class ResponseModelDouble {
  @JsonProperty("Result")
  private Double result = null;

  @JsonProperty("Error")
  private ErrorModel error = null;

  /**
   * <p>result.</p>
   *
   * @param result a {@link java.lang.Double} object.
   * @return a {@link com.lykke.hft.model.ResponseModelDouble} object.
   */
  public ResponseModelDouble result(Double result) {
    this.result = result;
    return this;
  }

  /**
   * Get result
   *
   * @return result
   */
  @ApiModelProperty(required = true, value = "")
  public Double getResult() {
    return result;
  }

  /**
   * <p>Setter for the field <code>result</code>.</p>
   *
   * @param result a {@link java.lang.Double} object.
   */
  public void setResult(Double result) {
    this.result = result;
  }

  /**
   * <p>error.</p>
   *
   * @param error a {@link com.lykke.hft.model.ErrorModel} object.
   * @return a {@link com.lykke.hft.model.ResponseModelDouble} object.
   */
  public ResponseModelDouble error(ErrorModel error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   *
   * @return error
   */
  @ApiModelProperty(value = "")
  public ErrorModel getError() {
    return error;
  }

  /**
   * <p>Setter for the field <code>error</code>.</p>
   *
   * @param error a {@link com.lykke.hft.model.ErrorModel} object.
   */
  public void setError(ErrorModel error) {
    this.error = error;
  }


  /** {@inheritDoc} */
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseModelDouble responseModelDouble = (ResponseModelDouble) o;
    return Objects.equals(this.result, responseModelDouble.result) &&
        Objects.equals(this.error, responseModelDouble.error);
  }

  /** {@inheritDoc} */
  @Override
  public int hashCode() {
    return Objects.hash(result, error);
  }


  /** {@inheritDoc} */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseModelDouble {\n");
    
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

